-- =====================================================================
-- Multi-tenancy Phase 4 — Espace CLIENT (marketplace).
--   * Role CLIENT (compte global, sans boutique fixe) rejoint ck_users_role.
--   * Commandes en ligne : orders + order_items, tables TENANT (boutique_id + RLS)
--     pour que le boutique-admin ne voie QUE ses commandes.
--   * Stock NON decremente ici (C3) : reserve a la confirmation (Phase 5).
--   * boutique_id : DEFAULT = tenant courant (pose par slug lors de la commande) ;
--     le CLIENT n'ayant pas de boutique fixe, c'est le slug qui fixe le tenant.
-- =====================================================================

ALTER TABLE users DROP CONSTRAINT ck_users_role;
ALTER TABLE users ADD  CONSTRAINT ck_users_role
    CHECK (role IN ('SUPER_ADMIN', 'ADMIN', 'VENDEUR', 'CLIENT'));

-- Un CLIENT est GLOBAL (aucune boutique fixe) : boutique_id devient nullable. Sur : un user a
-- tenant NULL est fail-closed cote RLS (voit 0 ligne), jamais une fuite.
ALTER TABLE users ALTER COLUMN boutique_id DROP NOT NULL;

CREATE TABLE orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference    VARCHAR(40)   NOT NULL,
    boutique_id  BIGINT        NOT NULL REFERENCES boutiques (id)
                     DEFAULT NULLIF(current_setting('app.current_boutique', true), '')::bigint,
    client_id    BIGINT        NOT NULL REFERENCES users (id),
    status       VARCHAR(20)   NOT NULL DEFAULT 'EN_ATTENTE',
    total_amount NUMERIC(12,2) NOT NULL,   -- calcule serveur (prix du tenant du slug)
    created_at   TIMESTAMP     NOT NULL DEFAULT now(),
    CONSTRAINT ck_orders_status CHECK (status IN ('EN_ATTENTE', 'CONFIRMEE', 'PRETE', 'RECUPEREE', 'ANNULEE')),
    CONSTRAINT uk_orders_boutique_reference UNIQUE (boutique_id, reference)
);
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders FORCE  ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON orders
    USING      (boutique_id = NULLIF(current_setting('app.current_boutique', true), '')::bigint)
    WITH CHECK (boutique_id = NULLIF(current_setting('app.current_boutique', true), '')::bigint);
CREATE INDEX idx_orders_boutique ON orders (boutique_id);
CREATE INDEX idx_orders_client   ON orders (client_id);

CREATE TABLE order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT        NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    variant_id  BIGINT        NOT NULL REFERENCES product_variant (id),
    quantity    INT           NOT NULL,
    unit_price  NUMERIC(12,2) NOT NULL,
    boutique_id BIGINT        NOT NULL REFERENCES boutiques (id)
                    DEFAULT NULLIF(current_setting('app.current_boutique', true), '')::bigint
);
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items FORCE  ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON order_items
    USING      (boutique_id = NULLIF(current_setting('app.current_boutique', true), '')::bigint)
    WITH CHECK (boutique_id = NULLIF(current_setting('app.current_boutique', true), '')::bigint);
CREATE INDEX idx_order_items_order ON order_items (order_id);

-- Runtime (sb_app). Les ALTER DEFAULT PRIVILEGES de V9 couvrent deja ces nouvelles tables,
-- mais on est explicite.
GRANT SELECT, INSERT, UPDATE, DELETE ON orders TO sb_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON order_items TO sb_app;
