-- =====================================================================
-- Multi-tenancy Phase 5 — Gestion des commandes cote boutique.
-- Journal des changements de statut d'une commande (historique + base des
-- notifications client). Table TENANT (boutique_id + RLS) : le boutique-admin
-- ne voit que l'historique de SES commandes.
-- =====================================================================

CREATE TABLE order_status_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT       NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    from_status VARCHAR(20),                    -- NULL = creation de la commande
    to_status   VARCHAR(20)  NOT NULL,
    changed_by  VARCHAR(120),                   -- nom de l'acteur (denormalise)
    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    boutique_id BIGINT       NOT NULL REFERENCES boutiques (id)
                    DEFAULT NULLIF(current_setting('app.current_boutique', true), '')::bigint,
    CONSTRAINT ck_osh_to_status CHECK (to_status IN ('EN_ATTENTE', 'CONFIRMEE', 'PRETE', 'RECUPEREE', 'ANNULEE'))
);
ALTER TABLE order_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_status_history FORCE  ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON order_status_history
    USING      (boutique_id = NULLIF(current_setting('app.current_boutique', true), '')::bigint)
    WITH CHECK (boutique_id = NULLIF(current_setting('app.current_boutique', true), '')::bigint);
CREATE INDEX idx_osh_order ON order_status_history (order_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON order_status_history TO sb_app;
