-- =====================================================================
-- accounts-permissions Phase A : compte GLOBAL + roles CONTEXTUELS.
--
-- users devient une IDENTITE (plus de role global ni de boutique figee). Le role
-- devient contextuel via shop_members (user <-> boutique <-> OWNER|VENDOR). Le
-- SUPER_ADMIN devient le flag is_platform_admin.
--
-- CHOIX : on CONSERVE les noms internes boutiques / boutique_id / app.current_boutique
-- (renommer 20 tables + policies RLS serait un risque inutile). "shop" == "boutique" ;
-- le header X-Shop-Id mappe boutique_id, et SET LOCAL reste app.current_boutique.
--
-- BACKFILL : preserve strictement l'existant (admin -> OWNER, vendeurs -> VENDOR,
-- SUPER_ADMIN -> is_platform_admin). Comptages avant/apres identiques.
-- =====================================================================

-- 1) Flag plateforme (ex-SUPER_ADMIN) + proprietaire de boutique.
ALTER TABLE users ADD COLUMN is_platform_admin BOOLEAN NOT NULL DEFAULT false;
UPDATE users SET is_platform_admin = true WHERE role = 'SUPER_ADMIN';

ALTER TABLE boutiques ADD COLUMN owner_user_id BIGINT REFERENCES users (id);
UPDATE boutiques b SET owner_user_id = (
    SELECT u.id FROM users u
    WHERE u.boutique_id = b.id AND u.role = 'ADMIN'
    ORDER BY u.id LIMIT 1);
-- owner_user_id reste NULLABLE : sur une base neuve, la boutique par defaut (creee par
-- V9) precede la creation de l'admin (DataSeeder) qui lui affectera le proprietaire.

-- 2) Membership contextuel. Table GLOBALE (pas de RLS ; accedee par la logique d'auth).
CREATE TABLE shop_members (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id    BIGINT       NOT NULL REFERENCES boutiques (id) ON DELETE CASCADE,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role       VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uk_shop_members UNIQUE (shop_id, user_id),
    CONSTRAINT ck_shop_members_role CHECK (role IN ('OWNER', 'VENDOR'))
);
CREATE INDEX idx_shop_members_user ON shop_members (user_id);
CREATE INDEX idx_shop_members_shop ON shop_members (shop_id);

-- 3) BACKFILL des memberships depuis role + boutique_id existants.
INSERT INTO shop_members (shop_id, user_id, role)
SELECT u.boutique_id, u.id, CASE WHEN u.role = 'ADMIN' THEN 'OWNER' ELSE 'VENDOR' END
FROM users u
WHERE u.role IN ('ADMIN', 'VENDEUR') AND u.boutique_id IS NOT NULL;

-- 4) users = identite pure : suppression du role global et de la boutique figee.
ALTER TABLE users DROP CONSTRAINT ck_users_role;
ALTER TABLE users DROP COLUMN role;
ALTER TABLE users DROP COLUMN boutique_id;

-- 5) Grants runtime (shop_members est globale).
GRANT SELECT, INSERT, UPDATE, DELETE ON shop_members TO sb_app;
