-- =====================================================================
-- V15 — Notifications in-app (par utilisateur / identite).
-- Table GLOBALE (identite), comme users/shop_members : PAS de boutique_id, PAS de RLS.
-- Alimentee au changement de statut d'une commande (OrderNotificationListener, apres commit).
-- =====================================================================
CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type       VARCHAR(40) NOT NULL,
    title      VARCHAR(160) NOT NULL,
    body       VARCHAR(400),
    order_id   BIGINT,
    is_read    BOOLEAN     NOT NULL DEFAULT false,
    created_at TIMESTAMP   NOT NULL DEFAULT now()
);

-- Acces typique : les notifications d'un user, non lues d'abord, recentes en tete.
CREATE INDEX idx_notifications_user ON notifications (user_id, is_read, created_at DESC);

-- Grants runtime (table globale, hors RLS).
GRANT SELECT, INSERT, UPDATE, DELETE ON notifications TO sb_app;
