-- =====================================================================
-- V17 — Abonnements client : un utilisateur SUIT une boutique (« following »).
-- Table GLOBALE (identite), comme notifications/shop_members : PAS de boutique_id RLS ici,
-- la ligne relie un user à une boutique.
-- =====================================================================
CREATE TABLE follows (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    shop_id    BIGINT    NOT NULL REFERENCES boutiques (id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uk_follows UNIQUE (user_id, shop_id)
);

CREATE INDEX idx_follows_user ON follows (user_id);
CREATE INDEX idx_follows_shop ON follows (shop_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON follows TO sb_app;
