-- =====================================================================
-- V19 — Favoris client (wishlist) : un utilisateur met un PRODUIT en favori.
-- Table GLOBALE (identite), comme follows/notifications/shop_members : PAS de boutique_id RLS ici,
-- la ligne relie un user à un produit. L'utilisateur ne voit que SES favoris (scope applicatif).
-- =====================================================================
CREATE TABLE favorites (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    product_id BIGINT    NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uk_favorites UNIQUE (user_id, product_id)
);

CREATE INDEX idx_favorites_user ON favorites (user_id);
CREATE INDEX idx_favorites_product ON favorites (product_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON favorites TO sb_app;
