-- =====================================================================
-- Smart Boutique — schema initial (baseline Flyway).
-- Fige le schema genere par les entites JPA. En prod : Flyway applique ce
-- script, puis Hibernate (ddl-auto=validate) verifie la concordance.
-- =====================================================================

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(20)  NOT NULL,
    active      BOOLEAN      NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'VENDEUR'))
);

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE products (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference      VARCHAR(255)  NOT NULL,
    name           VARCHAR(255)  NOT NULL,
    description    VARCHAR(1000),
    category_id    BIGINT,
    size           VARCHAR(255),
    color          VARCHAR(255),
    purchase_price NUMERIC(12,2),
    sale_price     NUMERIC(12,2),
    quantity       INTEGER       NOT NULL,
    seuil_alerte   INTEGER       NOT NULL,
    image_url      VARCHAR(255),
    qr_code        VARCHAR(255),
    created_at     TIMESTAMP     NOT NULL,
    CONSTRAINT uk_products_reference UNIQUE (reference),
    CONSTRAINT uk_products_qr_code UNIQUE (qr_code),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE sales (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id      BIGINT       NOT NULL,
    sale_date      TIMESTAMP    NOT NULL,
    payment_method VARCHAR(20)  NOT NULL,
    discount       NUMERIC(12,2),
    total_amount   NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_sales_seller FOREIGN KEY (seller_id) REFERENCES users (id),
    CONSTRAINT ck_sales_payment_method CHECK (payment_method IN ('ESPECES', 'CARTE', 'MIXTE'))
);

CREATE TABLE sale_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id     BIGINT        NOT NULL,
    product_id  BIGINT        NOT NULL,
    quantity    INTEGER       NOT NULL,
    unit_price  NUMERIC(12,2) NOT NULL,
    total_price NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_sale_items_sale FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT fk_sale_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE returns (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id     BIGINT      NOT NULL,
    product_id  BIGINT      NOT NULL,
    quantity    INTEGER     NOT NULL,
    reason      VARCHAR(500),
    return_date TIMESTAMP   NOT NULL,
    CONSTRAINT fk_returns_sale FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT fk_returns_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(255) NOT NULL,
    user_id    BIGINT       NOT NULL,
    expires_at TIMESTAMP    NOT NULL,
    used       BOOLEAN      NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT uk_password_reset_token UNIQUE (token),
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users (id)
);
