-- =====================================================================
-- Phase 9 : modele VARIANTES (couleur x taille). Migration des donnees existantes :
-- chaque produit devient UNE variante reprenant ses size/color/quantity/seuil, puis les
-- colonnes scalaires du produit sont supprimees. Idempotente pour une base vide (fresh prod).
-- =====================================================================

-- 1. Catalogue de couleurs
CREATE TABLE colors (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    hex  VARCHAR(7),
    CONSTRAINT uk_colors_name UNIQUE (name)
);

-- 2. Couleurs distinctes issues des produits existants (couleur vide -> "Unique")
INSERT INTO colors (name)
SELECT DISTINCT COALESCE(NULLIF(TRIM(color), ''), 'Unique')
FROM products
ON CONFLICT (name) DO NOTHING;

-- 4. Table des variantes
CREATE TABLE product_variant (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   BIGINT       NOT NULL,
    color_id     BIGINT       NOT NULL,
    size         VARCHAR(20)  NOT NULL,
    quantity     INTEGER      NOT NULL,
    seuil_alerte INTEGER      NOT NULL,
    reference    VARCHAR(255) NOT NULL,
    qr_code      VARCHAR(255),
    created_at   TIMESTAMP    NOT NULL,
    CONSTRAINT uk_variant_reference UNIQUE (reference),
    CONSTRAINT uk_variant_qr_code UNIQUE (qr_code),
    CONSTRAINT uk_variant_product_color_size UNIQUE (product_id, color_id, size),
    CONSTRAINT fk_variant_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_variant_color FOREIGN KEY (color_id) REFERENCES colors (id)
);

-- 5. Une variante par produit existant (reference = REF-SIZE-COLORSLUG)
INSERT INTO product_variant (product_id, color_id, size, quantity, seuil_alerte, reference, created_at)
SELECT p.id,
       c.id,
       sz.size,
       p.quantity,
       p.seuil_alerte,
       p.reference || '-' || UPPER(sz.size) || '-'
           || UPPER(REGEXP_REPLACE(c.name, '[^a-zA-Z0-9]+', '-', 'g')),
       COALESCE(p.created_at, NOW())
FROM products p
JOIN LATERAL (SELECT COALESCE(NULLIF(TRIM(p.size), ''), 'UNI') AS size) sz ON TRUE
JOIN colors c ON c.name = COALESCE(NULLIF(TRIM(p.color), ''), 'Unique');

UPDATE product_variant SET qr_code = reference;

-- 6. sale_items : repointer product_id -> variant_id + denormaliser couleur/taille
ALTER TABLE sale_items ADD COLUMN variant_id        BIGINT;
ALTER TABLE sale_items ADD COLUMN variant_reference VARCHAR(255);
ALTER TABLE sale_items ADD COLUMN product_name      VARCHAR(255);
ALTER TABLE sale_items ADD COLUMN color_name        VARCHAR(255);
ALTER TABLE sale_items ADD COLUMN size              VARCHAR(20);

UPDATE sale_items si
SET variant_id        = v.id,
    variant_reference = v.reference,
    product_name      = p.name,
    color_name        = c.name,
    size              = v.size
FROM product_variant v
JOIN products p ON p.id = v.product_id
JOIN colors   c ON c.id = v.color_id
WHERE v.product_id = si.product_id;   -- chaque produit n'a qu'une variante : mapping deterministe

ALTER TABLE sale_items ALTER COLUMN variant_id SET NOT NULL;
ALTER TABLE sale_items ALTER COLUMN variant_reference SET NOT NULL;
ALTER TABLE sale_items ALTER COLUMN product_name SET NOT NULL;
ALTER TABLE sale_items ADD CONSTRAINT fk_sale_items_variant FOREIGN KEY (variant_id) REFERENCES product_variant (id);
ALTER TABLE sale_items DROP CONSTRAINT fk_sale_items_product;
ALTER TABLE sale_items DROP COLUMN product_id;

-- 7. returns : repointer product_id -> variant_id
ALTER TABLE returns ADD COLUMN variant_id BIGINT;

UPDATE returns r
SET variant_id = v.id
FROM product_variant v
WHERE v.product_id = r.product_id;

ALTER TABLE returns ALTER COLUMN variant_id SET NOT NULL;
ALTER TABLE returns ADD CONSTRAINT fk_returns_variant FOREIGN KEY (variant_id) REFERENCES product_variant (id);
ALTER TABLE returns DROP CONSTRAINT fk_returns_product;
ALTER TABLE returns DROP COLUMN product_id;

-- 8. Supprimer les colonnes scalaires du produit (le stock/QR vivent sur la variante)
ALTER TABLE products DROP CONSTRAINT uk_products_qr_code;
ALTER TABLE products DROP COLUMN qr_code;
ALTER TABLE products DROP COLUMN size;
ALTER TABLE products DROP COLUMN color;
ALTER TABLE products DROP COLUMN quantity;
ALTER TABLE products DROP COLUMN seuil_alerte;
