-- =====================================================================
-- Reintegration : catalogue TAILLES gere, reutilise par les variantes.
-- Convertit product_variant.size (texte libre, issu de V2) en une FK size_id
-- vers une table sizes administrable (CRUD). S'applique en avant.
-- =====================================================================

-- 1) Catalogue de tailles.
CREATE TABLE sizes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label      VARCHAR(255) NOT NULL,
    position   INTEGER,
    created_at TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uk_sizes_label UNIQUE (label)
);

-- 2) Backfill : une taille par valeur distincte deja portee par les variantes.
INSERT INTO sizes (label, created_at)
SELECT DISTINCT TRIM(size), now()
FROM product_variant
WHERE size IS NOT NULL AND TRIM(size) <> '';

-- 3) FK size_id sur la variante.
ALTER TABLE product_variant ADD COLUMN size_id BIGINT;
UPDATE product_variant v SET size_id = s.id
FROM sizes s
WHERE TRIM(v.size) = s.label;
ALTER TABLE product_variant ALTER COLUMN size_id SET NOT NULL;
ALTER TABLE product_variant
    ADD CONSTRAINT fk_variant_size FOREIGN KEY (size_id) REFERENCES sizes (id);

-- 4) L'unicite (couleur+taille) par produit passe sur size_id.
ALTER TABLE product_variant DROP CONSTRAINT uk_variant_product_color_size;
ALTER TABLE product_variant
    ADD CONSTRAINT uk_variant_product_color_size UNIQUE (product_id, color_id, size_id);

-- 5) L'ancienne colonne texte n'est plus la source de verite.
ALTER TABLE product_variant DROP COLUMN size;
