-- =====================================================================
-- Reintegration : galerie de PHOTOS au niveau produit (product_images).
-- Remplace la colonne scalaire products.image_url par une table ordonnable.
-- La photo position 0 reste la couverture (exposee en imageUrl, non-regression).
-- S'applique en avant (apres V2 variants + V3 sizes).
-- =====================================================================

CREATE TABLE product_images (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT       NOT NULL,
    url        VARCHAR(255) NOT NULL,
    position   INTEGER      NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT fk_product_images_product FOREIGN KEY (product_id)
        REFERENCES products (id) ON DELETE CASCADE
);

CREATE INDEX idx_product_images_product_position ON product_images (product_id, position);

-- Backfill : l'image unique existante devient la couverture (position 0).
INSERT INTO product_images (product_id, url, position, created_at)
SELECT id, image_url, 0, now()
FROM products
WHERE image_url IS NOT NULL AND image_url <> '';

ALTER TABLE products DROP COLUMN image_url;
