-- =====================================================================
-- Module CREDITS (ventes a credit). Additif : ne touche ni sales, ni returns,
-- ni la logique de stock/CA existante. Un credit est une vente (1-1) augmentee
-- d'un client, d'une echeance et de paiements. Reste/statut DERIVES (non stockes).
-- =====================================================================

CREATE TABLE customers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    phone      VARCHAR(50),
    address    VARCHAR(500),
    created_at TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE credits (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id     BIGINT    NOT NULL,
    customer_id BIGINT    NOT NULL,
    due_date    DATE,
    cancelled   BOOLEAN   NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uk_credits_sale UNIQUE (sale_id),
    CONSTRAINT fk_credits_sale FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT fk_credits_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE INDEX idx_credits_customer ON credits (customer_id);

CREATE TABLE credit_payments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credit_id  BIGINT        NOT NULL,
    amount     NUMERIC(12,2) NOT NULL,
    method     VARCHAR(20),
    created_at TIMESTAMP     NOT NULL DEFAULT now(),
    CONSTRAINT fk_credit_payments_credit FOREIGN KEY (credit_id) REFERENCES credits (id)
);

CREATE INDEX idx_credit_payments_credit ON credit_payments (credit_id);
