-- =====================================================================
-- Module DETTES FOURNISSEURS (comptes a payer). Registre PUREMENT FINANCIER :
-- additif, aucun impact stock ni CA. Total SAISI (facture) ; reste/statut DERIVES.
-- Le lien produit est DESCRIPTIF (optionnel) et ne touche jamais l'inventaire.
-- =====================================================================

CREATE TABLE suppliers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    phone      VARCHAR(50),
    address    VARCHAR(500),
    created_at TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE supplier_debts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id       BIGINT        NOT NULL,
    total_amount      NUMERIC(12,2) NOT NULL,
    due_date          DATE,
    invoice_reference VARCHAR(255),
    description       VARCHAR(1000),
    product_id        BIGINT,
    created_at        TIMESTAMP     NOT NULL DEFAULT now(),
    CONSTRAINT fk_debts_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_debts_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_debts_supplier ON supplier_debts (supplier_id);

CREATE TABLE debt_payments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_id    BIGINT        NOT NULL,
    amount     NUMERIC(12,2) NOT NULL,
    method     VARCHAR(20),
    created_at TIMESTAMP     NOT NULL DEFAULT now(),
    CONSTRAINT fk_debt_payments_debt FOREIGN KEY (debt_id) REFERENCES supplier_debts (id)
);

CREATE INDEX idx_debt_payments_debt ON debt_payments (debt_id);
