-- =====================================================================
-- Feature A : modes de paiement multiples (tenders) + TICKET CADEAU.
-- Additif : la vente passe d'un paymentMethod unique a une LISTE de tenders
-- (especes/carte/ticket cadeau, combinables). CA et stock INCHANGES.
-- Montants en NUMERIC(12,2) pour rester coherent avec le reste du systeme.
-- =====================================================================

CREATE TABLE sale_payments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id       BIGINT        NOT NULL REFERENCES sales (id) ON DELETE CASCADE,
    method        VARCHAR(20)   NOT NULL,   -- ESPECES | CARTE | TICKET_CADEAU
    amount        NUMERIC(12,2) NOT NULL,
    issuer        VARCHAR(20),               -- PLUXEE | JOKER | AUTRE (si TICKET_CADEAU)
    ticket_code   VARCHAR(120),              -- chaine scannee (QR ou code-barres)
    ticket_serial VARCHAR(80),               -- N° imprime (optionnel)
    ticket_expiry DATE,                       -- date d'expiration imprimee
    created_at    TIMESTAMP     NOT NULL DEFAULT now(),
    CONSTRAINT ck_sale_payments_method CHECK (method IN ('ESPECES', 'CARTE', 'TICKET_CADEAU'))
);

CREATE INDEX idx_sale_payments_sale ON sale_payments (sale_id);

-- Usage unique GLOBAL du ticket cadeau (A4) : un code encaisse une seule fois,
-- toutes ventes confondues. Reutilisation -> violation -> 409 cote service.
CREATE UNIQUE INDEX uq_gift_ticket_code
    ON sale_payments (ticket_code)
    WHERE method = 'TICKET_CADEAU';
