-- =====================================================================
-- Feature B : Acompte / Reservation (layaway).
-- Le client verse un ACOMPTE, le produit est RETENU en boutique (reserve,
-- hors stock disponible) ; il le recupere une fois SOLDE. Passe l'echeance
-- sans solder -> EXPIRED + stock rendu.
--
--   * Stock retenu a la creation (B2), rendu a l'expiration/annulation.
--   * Acompte = DEPOT (passif) ; le CA est reconnu A LA CLOTURE (B3) : la
--     vente (sales) n'est creee qu'au passage COMPLETED, SANS re-decrementer
--     le stock (deja retenu). reservations.sale_id lie la reservation a cette
--     vente de reconnaissance du CA.
--   * Montants en NUMERIC(12,2), coherent avec le reste du systeme
--     (le handoff suggerait 12,3 ; on garde 12,2 partout).
-- =====================================================================

CREATE TABLE reservations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference         VARCHAR(40)   NOT NULL UNIQUE,
    customer_name     VARCHAR(120)  NOT NULL,
    customer_phone    VARCHAR(40),
    seller_id         BIGINT        NOT NULL REFERENCES users (id),
    status            VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',   -- ACTIVE | COMPLETED | EXPIRED | CANCELLED
    total_amount      NUMERIC(12,2) NOT NULL,                    -- calcule serveur
    deposit_forfeited BOOLEAN       NOT NULL DEFAULT FALSE,      -- acompte retenu (B6) a l'expiration/annulation
    sale_id           BIGINT        REFERENCES sales (id),       -- vente de reconnaissance du CA (a COMPLETED)
    created_at        TIMESTAMP     NOT NULL DEFAULT now(),
    due_date          TIMESTAMP     NOT NULL,
    closed_at         TIMESTAMP,
    CONSTRAINT ck_reservations_status CHECK (status IN ('ACTIVE', 'COMPLETED', 'EXPIRED', 'CANCELLED'))
);

CREATE INDEX idx_reservations_status   ON reservations (status);
CREATE INDEX idx_reservations_due_date ON reservations (due_date);

CREATE TABLE reservation_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id    BIGINT        NOT NULL REFERENCES reservations (id) ON DELETE CASCADE,
    variant_id        BIGINT        NOT NULL REFERENCES product_variant (id),
    quantity          INT           NOT NULL,
    unit_price        NUMERIC(12,2) NOT NULL,
    -- Denormalisation (figee a la reservation, pour l'affichage et la vente de cloture).
    variant_reference VARCHAR(255)  NOT NULL,
    product_name      VARCHAR(255)  NOT NULL,
    color_name        VARCHAR(255),
    size              VARCHAR(20)
);

CREATE INDEX idx_reservation_items_reservation ON reservation_items (reservation_id);

-- Journal des versements (meme pattern que Credits/Dettes) : methode + montant.
CREATE TABLE reservation_payments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT        NOT NULL REFERENCES reservations (id) ON DELETE CASCADE,
    amount         NUMERIC(12,2) NOT NULL,
    method         VARCHAR(20)   NOT NULL,   -- ESPECES | CARTE | TICKET_CADEAU
    seller_id      BIGINT        NOT NULL REFERENCES users (id),
    created_at     TIMESTAMP     NOT NULL DEFAULT now(),
    CONSTRAINT ck_reservation_payments_method CHECK (method IN ('ESPECES', 'CARTE', 'TICKET_CADEAU'))
);

CREATE INDEX idx_reservation_payments_reservation ON reservation_payments (reservation_id);
