-- =====================================================================
-- Multi-tenancy Phase 1 — Fondation.
--
-- Modele : schema partage + colonne boutique_id sur chaque table tenant + RLS
-- PostgreSQL (defense en profondeur). Isolation transparente :
--   * boutique_id porte un DEFAULT SQL = tenant courant
--     (NULLIF(current_setting('app.current_boutique', true), '')::bigint) -> les
--     INSERT applicatifs (qui omettent la colonne) recoivent automatiquement le
--     bon tenant ; les entites JPA restent inchangees.
--   * policy tenant_isolation (USING + WITH CHECK) => lecture/ecriture limitees au
--     tenant courant. NULLIF(..,'') : un GUC RESET revient a '' (pas NULL).
--   * FORCE ROW LEVEL SECURITY : la RLS s'applique meme au proprietaire ; l'app
--     runtime se connecte via le role NON-SUPERUSER sb_app (un superuser bypasse).
--
-- users : boutique_id + scoping applicatif MAIS PAS de RLS (le login est
-- pre-tenant) ; email reste UNIQUE GLOBAL. password_reset_tokens : hors tenant
-- (accede pre-auth par token). boutiques : registre des tenants (hors RLS).
--
-- T6 : boutique par defaut + backfill de TOUTES les lignes existantes, puis NOT NULL.
-- =====================================================================

-- 1) Registre des tenants + boutique par defaut.
CREATE TABLE boutiques (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    slug       VARCHAR(140) NOT NULL UNIQUE,
    status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT ck_boutiques_status CHECK (status IN ('ACTIVE', 'SUSPENDED'))
);
INSERT INTO boutiques (name, slug) VALUES ('Boutique par defaut', 'default');

-- 2) Role applicatif runtime NON-SUPERUSER (mot de passe via placeholder Flyway).
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'sb_app') THEN
        CREATE ROLE sb_app LOGIN PASSWORD '${app_role_password}' NOSUPERUSER;
    END IF;
END $$;

-- 3) Tables TENANT : boutique_id + backfill + NOT NULL + DEFAULT tenant courant
--    + RLS/FORCE + policy + index + grants. (loop DRY sur la liste des tables.)
DO $$
DECLARE
    t        text;
    def_id   bigint;
    tenant_tables text[] := ARRAY[
        'categories','colors','sizes','products','product_variant','product_images',
        'customers','suppliers','sales','sale_items','sale_payments','returns',
        'credits','credit_payments','supplier_debts','debt_payments',
        'reservations','reservation_items','reservation_payments'
    ];
    guc constant text := 'NULLIF(current_setting(''app.current_boutique'', true), '''')::bigint';
BEGIN
    SELECT id INTO def_id FROM boutiques WHERE slug = 'default';
    FOREACH t IN ARRAY tenant_tables LOOP
        EXECUTE format('ALTER TABLE %I ADD COLUMN boutique_id bigint REFERENCES boutiques(id)', t);
        EXECUTE format('UPDATE %I SET boutique_id = %L', t, def_id);
        EXECUTE format('ALTER TABLE %I ALTER COLUMN boutique_id SET NOT NULL', t);
        EXECUTE format('ALTER TABLE %I ALTER COLUMN boutique_id SET DEFAULT %s', t, guc);
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
        EXECUTE format(
            'CREATE POLICY tenant_isolation ON %I USING (boutique_id = %s) WITH CHECK (boutique_id = %s)',
            t, guc, guc);
        EXECUTE format('CREATE INDEX idx_%s_boutique ON %I (boutique_id)', t, t);
        EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO sb_app', t);
    END LOOP;
END $$;

-- 4) users : boutique_id (scoping applicatif) SANS RLS ; email reste global.
ALTER TABLE users ADD COLUMN boutique_id bigint REFERENCES boutiques(id);
UPDATE users SET boutique_id = (SELECT id FROM boutiques WHERE slug = 'default');
ALTER TABLE users ALTER COLUMN boutique_id SET NOT NULL;
ALTER TABLE users ALTER COLUMN boutique_id SET DEFAULT NULLIF(current_setting('app.current_boutique', true), '')::bigint;
CREATE INDEX idx_users_boutique ON users (boutique_id);

-- 5) Unicite composite par tenant (T5). Le QR se resout dans le tenant du vendeur.
ALTER TABLE products        DROP CONSTRAINT uk_products_reference;
ALTER TABLE products        ADD  CONSTRAINT uk_products_boutique_reference UNIQUE (boutique_id, reference);
ALTER TABLE product_variant DROP CONSTRAINT uk_variant_reference;
ALTER TABLE product_variant ADD  CONSTRAINT uk_variant_boutique_reference UNIQUE (boutique_id, reference);
ALTER TABLE product_variant DROP CONSTRAINT uk_variant_qr_code;
ALTER TABLE product_variant ADD  CONSTRAINT uk_variant_boutique_qr UNIQUE (boutique_id, qr_code);
ALTER TABLE categories      DROP CONSTRAINT uk_categories_name;
ALTER TABLE categories      ADD  CONSTRAINT uk_categories_boutique_name UNIQUE (boutique_id, name);
ALTER TABLE colors          DROP CONSTRAINT uk_colors_name;
ALTER TABLE colors          ADD  CONSTRAINT uk_colors_boutique_name UNIQUE (boutique_id, name);
ALTER TABLE sizes           DROP CONSTRAINT uk_sizes_label;
ALTER TABLE sizes           ADD  CONSTRAINT uk_sizes_boutique_label UNIQUE (boutique_id, label);
ALTER TABLE reservations    DROP CONSTRAINT reservations_reference_key;
ALTER TABLE reservations    ADD  CONSTRAINT uk_reservations_boutique_reference UNIQUE (boutique_id, reference);

-- 6) Grants runtime pour sb_app (schema, users, sequences, boutiques + objets futurs).
GRANT USAGE ON SCHEMA public TO sb_app;
GRANT SELECT ON boutiques TO sb_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON users TO sb_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON password_reset_tokens TO sb_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sb_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sb_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO sb_app;
